packages:
  - packages/*

ignoredBuiltDependencies:
  - '@applemusic-like-lyrics/core'
  - '@applemusic-like-lyrics/lyric'
  - '@applemusic-like-lyrics/react'
  - '@swc/core'
  - esbuild
  - msw

onlyBuiltDependencies: esbuild
