export const LIMITS = {
  ROOM_PASSWORD_MAX_LENGTH: 32,
  ROOM_NAME_MAX_LENGTH: 30,
  NICKNAME_MAX_LENGTH: 20,
  CHAT_CONTENT_MAX_LENGTH: 500,
  CHAT_HISTORY_MAX: 200,
  CHAT_RATE_LIMIT_PER_SECOND: 5,
  QUEUE_MAX_SIZE: 100,
} as const

export const TIMING = {
  SYNC_BROADCAST_INTERVAL_MS: 10_000,
  ROOM_GRACE_PERIOD_MS: 30_000,
  PLAYER_NEXT_DEBOUNCE_MS: 2_000,
} as const
